name: Build FrostKeys APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Compilar APK
        run: ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: FrostKeys-debug
          path: "**/build/outputs/apk/**/*.apk"
